name: Run React tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Run tests
        run: |
          cd packages/registry-ui
          npm i -g yarn
          yarn
          CI=true yarn test
